# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_spectver2.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(968, 527)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(1000, 480))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.frame_6 = QtGui.QFrame(self.tab_2)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.f_ROI = GraphicsView(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_ROI.sizePolicy().hasHeightForWidth())
        self.f_ROI.setSizePolicy(sizePolicy)
        self.f_ROI.setMinimumSize(QtCore.QSize(320, 240))
        self.f_ROI.setMaximumSize(QtCore.QSize(320, 240))
        self.f_ROI.setObjectName(_fromUtf8("f_ROI"))
        self.verticalLayout_5.addWidget(self.f_ROI)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_4 = QtGui.QFrame(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 4, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.laserHigh = QtGui.QLineEdit(self.groupBox_3)
        self.laserHigh.setObjectName(_fromUtf8("laserHigh"))
        self.gridLayout_3.addWidget(self.laserHigh, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 2, 0, 1, 1)
        self.projHigh = QtGui.QLineEdit(self.groupBox_3)
        self.projHigh.setObjectName(_fromUtf8("projHigh"))
        self.gridLayout_3.addWidget(self.projHigh, 3, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 6, 0, 1, 1)
        self.laserLow = QtGui.QLineEdit(self.groupBox_3)
        self.laserLow.setObjectName(_fromUtf8("laserLow"))
        self.gridLayout_3.addWidget(self.laserLow, 5, 0, 1, 1)
        self.projLow = QtGui.QLineEdit(self.groupBox_3)
        self.projLow.setObjectName(_fromUtf8("projLow"))
        self.gridLayout_3.addWidget(self.projLow, 7, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.buttonUpdateProjection = QtGui.QPushButton(self.groupBox_3)
        self.buttonUpdateProjection.setObjectName(_fromUtf8("buttonUpdateProjection"))
        self.verticalLayout_6.addWidget(self.buttonUpdateProjection)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame_3 = QtGui.QFrame(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_12 = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_2.addWidget(self.label_12)
        self.coor = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coor.sizePolicy().hasHeightForWidth())
        self.coor.setSizePolicy(sizePolicy)
        self.coor.setObjectName(_fromUtf8("coor"))
        self.verticalLayout_2.addWidget(self.coor)
        self.groupBox = QtGui.QGroupBox(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 131, 141))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.line_mincol = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.line_mincol.setObjectName(_fromUtf8("line_mincol"))
        self.gridLayout_2.addWidget(self.line_mincol, 0, 1, 1, 1)
        self.line_maxcol = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.line_maxcol.setObjectName(_fromUtf8("line_maxcol"))
        self.gridLayout_2.addWidget(self.line_maxcol, 1, 1, 1, 1)
        self.line_minrow = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.line_minrow.setObjectName(_fromUtf8("line_minrow"))
        self.gridLayout_2.addWidget(self.line_minrow, 2, 1, 1, 1)
        self.line_maxrow = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.line_maxrow.setObjectName(_fromUtf8("line_maxrow"))
        self.gridLayout_2.addWidget(self.line_maxrow, 3, 1, 1, 1)
        self.buttonUpdateROI = QtGui.QPushButton(self.groupBox)
        self.buttonUpdateROI.setGeometry(QtCore.QRect(30, 170, 75, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonUpdateROI.sizePolicy().hasHeightForWidth())
        self.buttonUpdateROI.setSizePolicy(sizePolicy)
        self.buttonUpdateROI.setObjectName(_fromUtf8("buttonUpdateROI"))
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.figure1 = GraphicsView(self.tab)
        self.figure1.setAutoFillBackground(False)
        self.figure1.setObjectName(_fromUtf8("figure1"))
        self.verticalLayout_4.addWidget(self.figure1)
        self.figure2 = PlotWidget(self.tab)
        self.figure2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.figure2.setFrameShadow(QtGui.QFrame.Sunken)
        self.figure2.setObjectName(_fromUtf8("figure2"))
        self.verticalLayout_4.addWidget(self.figure2)
        self.frame_5 = QtGui.QFrame(self.tab)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(self.frame_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lineFilename = QtGui.QLineEdit(self.frame_5)
        self.lineFilename.setObjectName(_fromUtf8("lineFilename"))
        self.horizontalLayout_4.addWidget(self.lineFilename)
        self.buttonGrab = QtGui.QPushButton(self.frame_5)
        self.buttonGrab.setObjectName(_fromUtf8("buttonGrab"))
        self.horizontalLayout_4.addWidget(self.buttonGrab)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(1000, 480))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_2 = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.buttonStart = QtGui.QPushButton(self.frame_2)
        self.buttonStart.setStyleSheet(_fromUtf8(""))
        self.buttonStart.setObjectName(_fromUtf8("buttonStart"))
        self.horizontalLayout.addWidget(self.buttonStart)
        self.buttonStop = QtGui.QPushButton(self.frame_2)
        self.buttonStop.setStyleSheet(_fromUtf8(""))
        self.buttonStop.setObjectName(_fromUtf8("buttonStop"))
        self.horizontalLayout.addWidget(self.buttonStop)
        self.verticalLayout.addWidget(self.frame_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.sliderCont = QtGui.QSlider(self.frame)
        self.sliderCont.setMaximum(255)
        self.sliderCont.setOrientation(QtCore.Qt.Horizontal)
        self.sliderCont.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.sliderCont.setTickInterval(50)
        self.sliderCont.setObjectName(_fromUtf8("sliderCont"))
        self.gridLayout.addWidget(self.sliderCont, 5, 0, 1, 1)
        self.sliderSat = QtGui.QSlider(self.frame)
        self.sliderSat.setMaximum(255)
        self.sliderSat.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSat.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.sliderSat.setTickInterval(50)
        self.sliderSat.setObjectName(_fromUtf8("sliderSat"))
        self.gridLayout.addWidget(self.sliderSat, 7, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 13, 0, 1, 1)
        self.sliderWB = QtGui.QSlider(self.frame)
        self.sliderWB.setMaximum(10000)
        self.sliderWB.setSingleStep(500)
        self.sliderWB.setPageStep(1000)
        self.sliderWB.setOrientation(QtCore.Qt.Horizontal)
        self.sliderWB.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.sliderWB.setTickInterval(1000)
        self.sliderWB.setObjectName(_fromUtf8("sliderWB"))
        self.gridLayout.addWidget(self.sliderWB, 14, 0, 1, 1)
        self.sliderBright = QtGui.QSlider(self.frame)
        self.sliderBright.setMaximum(255)
        self.sliderBright.setOrientation(QtCore.Qt.Horizontal)
        self.sliderBright.setInvertedAppearance(False)
        self.sliderBright.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.sliderBright.setTickInterval(50)
        self.sliderBright.setObjectName(_fromUtf8("sliderBright"))
        self.gridLayout.addWidget(self.sliderBright, 2, 0, 1, 1)
        self.sliderGain = QtGui.QSlider(self.frame)
        self.sliderGain.setMaximum(255)
        self.sliderGain.setOrientation(QtCore.Qt.Horizontal)
        self.sliderGain.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.sliderGain.setTickInterval(50)
        self.sliderGain.setObjectName(_fromUtf8("sliderGain"))
        self.gridLayout.addWidget(self.sliderGain, 9, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.sliderExpo = QtGui.QSlider(self.frame)
        self.sliderExpo.setMinimum(1)
        self.sliderExpo.setMaximum(7)
        self.sliderExpo.setOrientation(QtCore.Qt.Horizontal)
        self.sliderExpo.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.sliderExpo.setTickInterval(1)
        self.sliderExpo.setObjectName(_fromUtf8("sliderExpo"))
        self.gridLayout.addWidget(self.sliderExpo, 12, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 8, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 10, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonCalibrate = QtGui.QPushButton(self.frame)
        self.buttonCalibrate.setObjectName(_fromUtf8("buttonCalibrate"))
        self.verticalLayout.addWidget(self.buttonCalibrate)
        self.horizontalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 968, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.figure1, self.sliderGain)
        MainWindow.setTabOrder(self.sliderGain, self.buttonStart)
        MainWindow.setTabOrder(self.buttonStart, self.sliderExpo)
        MainWindow.setTabOrder(self.sliderExpo, self.figure2)
        MainWindow.setTabOrder(self.figure2, self.sliderSat)
        MainWindow.setTabOrder(self.sliderSat, self.sliderCont)
        MainWindow.setTabOrder(self.sliderCont, self.sliderBright)
        MainWindow.setTabOrder(self.sliderBright, self.buttonStop)
        MainWindow.setTabOrder(self.buttonStop, self.sliderWB)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Spectrometer v2.0", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Projection Settings:", None))
        self.label_14.setText(_translate("MainWindow", "Low Wavelength (nm):", None))
        self.label_13.setText(_translate("MainWindow", "High Wavelength (nm):", None))
        self.label_15.setText(_translate("MainWindow", "Projection Column:", None))
        self.label_16.setText(_translate("MainWindow", "Projection Column:", None))
        self.buttonUpdateProjection.setText(_translate("MainWindow", "Update Proj.", None))
        self.label_12.setText(_translate("MainWindow", "Clicked at:", None))
        self.coor.setText(_translate("MainWindow", "(0,0)", None))
        self.groupBox.setTitle(_translate("MainWindow", "ROI Settings:", None))
        self.label_9.setText(_translate("MainWindow", "Max. Col:", None))
        self.label_10.setText(_translate("MainWindow", "Min. Row:", None))
        self.label_8.setText(_translate("MainWindow", "Min. Col:", None))
        self.label_11.setText(_translate("MainWindow", "Max.Row:", None))
        self.buttonUpdateROI.setText(_translate("MainWindow", "Update ROI", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Calibration", None))
        self.label_7.setText(_translate("MainWindow", "Filename:", None))
        self.buttonGrab.setText(_translate("MainWindow", "Save Spectrum Data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Analysis", None))
        self.buttonStart.setText(_translate("MainWindow", "Start   ", None))
        self.buttonStop.setText(_translate("MainWindow", "Stop ", None))
        self.label.setText(_translate("MainWindow", "Brightness", None))
        self.label_6.setText(_translate("MainWindow", "White Balance", None))
        self.label_2.setText(_translate("MainWindow", "Saturation", None))
        self.label_4.setText(_translate("MainWindow", "Gain", None))
        self.label_3.setText(_translate("MainWindow", "Contrast", None))
        self.label_5.setText(_translate("MainWindow", "Exposure", None))
        self.buttonCalibrate.setText(_translate("MainWindow", "Normalize", None))

from pyqtgraph import GraphicsView, PlotWidget
